### ISSUE TITLE
package name in vue preset

### ISSUE THREAD

**Issue by tobiasfeil** [GregYankovoy/vue-cli-plugin-bootstrap-vue#7]
I'm trying to create a vue preset that adds this plugin when creating a vue project.
In the preset files, the sections of other plugins look like this:
`"@vue/cli-plugin-unit-jest": {},`
However, when I try to add
`"@vue/cli-plugin-bootstrap-vue": {},`
I get an error
`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vue%2fcli-plugin-bootstrap-vue - Not found
`
Is this because I specified the wrong name of this package?

**Comment by GregYankovoy** [comment]
I think since this is not an official vue plugin, you would have to specify this repository rather than "@vue".  Try "gregyankovoy/vue-cli-plugin-bootstrap-vue".

**Comment by tobiasfeil** [comment]
Thanks, I'll try that.
